// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwqolpibbkpuqfcspgji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3cW9scGliYmtwdXFmY3NwZ2ppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NjA1MDAsImV4cCI6MjA3MTUzNjUwMH0.GJ8dcVqPrMyps1AVL-DbvlXX1ZF1mj6aM0SMz5SDV5A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});